language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
      install:
        - pip install coverage
        - pip install coveralls
      script:
        - PYTHONPATH=code coverage run tests/test_wiki2beamer.py
        - coveralls
install:
script:
  - PYTHONPATH=code python tests/test_wiki2beamer.py
notifications:
  email: false
